config/routes.rb
Rails.application.routes.draw do
  

  get 'goal/index'
  post 'goal/save'
  get 'page/about'

  get 'page/contact'

  devise_for :users

  root 'page#home'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def americanDateFormatToSqlFormat date
  	if date.empty?
  		return nil
  	end
  	splittedDate  = date.split('/')
  	sqlDateFormat = DateTime.new(splittedDate[2].to_i,splittedDate[0].to_i,splittedDate[1].to_i)
  	return sqlDateFormat.to_formatted_s(:db)
  end
end

app/controllers/goal_controller.rb
class GoalController < ApplicationController
before_action :authenticate_user!
  def index
  	@goal_short_period = Goal.where(id_user: current_user.id, type_period: 1)
  	@goal_mid_period   = Goal.where(id_user: current_user.id, type_period: 2)
  	@goal_lomg_period  = Goal.where(id_user: current_user.id, type_period: 3)
  end

  def save
  	if Goal.where(id_user: current_user.id, type_period: 1).empty?
	  	goal = Goal.new
	else
		goal = Goal.where(id_user: current_user.id, type_period: 1)[0]
	end
  	goal.id_user      = current_user.id
  	goal.what         = params[:what_1]
  	goal.cost         = params[:cost_1]
  	goal.when         = americanDateFormatToSqlFormat(params[:when_1])
  	goal.how          = params[:how_1]
  	goal.where_invest = params[:where_invest_1]
  	goal.type_period  = 1
  	goal.save
	
	if Goal.where(id_user: current_user.id, type_period: 2).empty?
		goal2 = Goal.new
	else
		goal2 = Goal.where(id_user: current_user.id, type_period: 2)[0]
	end
  	goal2.id_user      = current_user.id
  	goal2.what         = params[:what_2]
  	goal2.cost         = params[:cost_2]
  	goal2.when         = americanDateFormatToSqlFormat(params[:when_2])
  	goal2.how          = params[:how_2]
  	goal2.where_invest = params[:where_invest_2]
  	goal2.type_period  = 2
  	goal2.save

  	if Goal.where(id_user: current_user.id, type_period: 3).empty?
  		goal3 = Goal.new
  	else
  		goal3 = Goal.where(id_user: current_user.id, type_period: 3)[0]
  	end
  	goal3.id_user      = current_user.id
  	goal3.what         = params[:what_3]
  	goal3.cost         = params[:cost_3]
  	goal3.when         = americanDateFormatToSqlFormat(params[:when_3])
  	goal3.how          = params[:how_3]
  	goal3.where_invest = params[:where_invest_3]
  	goal3.type_period  = 3
  	goal3.save
  	redirect_to goal_index_path
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
before_action :authenticate_user!, only: [:about, :contact]
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/goal/index.html.erb
<div class="table-responsive">
<% if @goal_short_period.empty? %>
<%end%>
	<%= form_tag({controller: "goal", action: "save"}, method: "post", class: "nifty_form") do %>
		<table class="table table-bordered .table-condensed">
			<thead>
				<tr>
					<th>Months and years</th>
					<th>What?</th>
					<th>Cost</th>
					<th>When do I want to fulfill it?</th>
					<th>How am I going to achieve it?</th>
					<th>Where am I going to invest?</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Short period</td>
					<td>
						<% if @goal_short_period.empty? %>
							<%= text_field_tag 'what_1', nil, class: 'form-control', placeholder: 'What?' %>
						<% else %>
							<%= text_field_tag 'what_1', @goal_short_period[0].what, class: 'form-control', placeholder: 'What?' %>
						<%end%>
					</td>
					<td>
						<% if @goal_short_period.empty? %>
							<%= text_field_tag 'cost_1', nil, class: 'form-control', placeholder: 'Cost' %>
						<% else %>
							<%= text_field_tag 'cost_1', @goal_short_period[0].cost, class: 'form-control', placeholder: 'Cost' %>
						<%end%>
					</td>
					<td>
						<% if @goal_short_period.empty? || @goal_short_period[0].when.nil? %>
							<%= text_field_tag 'when_1', nil, class: 'form-control', placeholder: 'When do I want to fulfill it??' %>
						<% else %>
							<%= text_field_tag 'when_1', @goal_short_period[0].when.to_time.strftime("%m/%d/%Y"), class: 'form-control', placeholder: 'When do I want to fulfill it??' %>
						<%end%>
					</td>
					<td>
						<% if @goal_short_period.empty? %>
							<%= text_field_tag 'how_1', nil, class: 'form-control', placeholder: 'How am I going to achieve it?' %>
						<% else %>
							<%= text_field_tag 'how_1', @goal_short_period[0].how, class: 'form-control', placeholder: 'How am I going to achieve it?' %>
						<%end%>
					</td>
					<td>
						<% if @goal_short_period.empty? %>
							<%= text_field_tag 'where_invest_1', nil, class: 'form-control', placeholder: 'Where am I going to invest?' %>
						<% else %>
							<%= text_field_tag 'where_invest_1', @goal_short_period[0].where_invest, class: 'form-control', placeholder: 'Where am I going to invest?' %>
						<%end%>
					</td>
				</tr>
				<tr>
					<td>Mid period</td>
					<td>
						<% if @goal_mid_period.empty? %>
							<%= text_field_tag 'what_2', nil, class: 'form-control', placeholder: 'What?' %>
						<% else %>
							<%= text_field_tag 'what_2', @goal_mid_period[0].what, class: 'form-control', placeholder: 'What?' %>
						<%end%>
					</td>
					<td>
						<% if @goal_mid_period.empty? %>
							<%= text_field_tag 'cost_2', nil, class: 'form-control', placeholder: 'Cost' %>
						<% else %>
							<%= text_field_tag 'cost_2', @goal_mid_period[0].cost, class: 'form-control', placeholder: 'Cost' %>
						<%end%>
					</td>
					<td>
						<% if @goal_mid_period.empty? || @goal_mid_period[0].when.nil? %>
							<%= text_field_tag 'when_2', nil, class: 'form-control', placeholder: 'When do I want to fulfill it??' %>
						<% else %>
							<%= text_field_tag 'when_2', @goal_mid_period[0].when.to_time.strftime("%m/%d/%Y"), class: 'form-control', placeholder: 'When do I want to fulfill it??' %>
						<%end%>
					</td>
					<td>
						<% if @goal_mid_period.empty? %>
							<%= text_field_tag 'how_2', nil, class: 'form-control', placeholder: 'How am I going to achieve it?' %>
						<% else %>
							<%= text_field_tag 'how_2', @goal_mid_period[0].how, class: 'form-control', placeholder: 'How am I going to achieve it?' %>
						<%end%>
					</td>
					<td>
						<% if @goal_mid_period.empty? %>
							<%= text_field_tag 'where_invest_2', nil, class: 'form-control', placeholder: 'Where am I going to invest?' %>
						<% else %>
							<%= text_field_tag 'where_invest_2', @goal_mid_period[0].where_invest, class: 'form-control', placeholder: 'Where am I going to invest?' %>
						<%end%>
					</td>
				</tr>
				<tr>
					<td>Long period</td>
					<td>
						<% if @goal_lomg_period.empty? %>
							<%= text_field_tag 'what_3', nil, class: 'form-control', placeholder: 'What?' %>
						<% else %>
							<%= text_field_tag 'what_3', @goal_lomg_period[0].what, class: 'form-control', placeholder: 'What?' %>
						<%end%>
					</td>
					<td>
						<% if @goal_lomg_period.empty? %>
							<%= text_field_tag 'cost_3', nil, class: 'form-control', placeholder: 'Cost' %>
						<% else %>
							<%= text_field_tag 'cost_3', @goal_lomg_period[0].cost, class: 'form-control', placeholder: 'Cost' %>
						<%end%>
						
					</td>
					<td>
						<% if @goal_lomg_period.empty? || @goal_lomg_period[0].when.nil? %>
							<%= text_field_tag 'when_3', nil, class: 'form-control', placeholder: 'When do I want to fulfill it??' %>
						<% else %>
							<%= text_field_tag 'when_3', @goal_lomg_period[0].when.to_time.strftime("%m/%d/%Y"), class: 'form-control', placeholder: 'When do I want to fulfill it??' %>
						<%end%>
					</td>
					<td>
						<% if @goal_lomg_period.empty? %>
							<%= text_field_tag 'how_3', nil, class: 'form-control', placeholder: 'How am I going to achieve it?' %>
						<% else %>
							<%= text_field_tag 'how_3', @goal_lomg_period[0].how, class: 'form-control', placeholder: 'How am I going to achieve it?' %>
						<%end%>
					</td>
					<td>
						<% if @goal_lomg_period.empty? %>
							<%= text_field_tag 'where_invest_3', nil, class: 'form-control', placeholder: 'Where am I going to invest?' %>
						<% else %>
							<%= text_field_tag 'where_invest_3', @goal_lomg_period[0].where_invest, class: 'form-control', placeholder: 'Where am I going to invest?' %>
						<%end%>
					</td>
				</tr>
			</tbody>
		</table>
		<%= submit_tag("Save Data", :class => 'btn btn-lg btn-primary btn-block') %>
	<% end %>
</div>

<script>
	$(function()
	{
		$('#when_1').datepicker();
		$('#when_2').datepicker();
		$('#when_3').datepicker();
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Manage your money" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- <a class="navbar-brand" href="#">Manage your money</a> -->
        <%= link_to 'Manage your money', root_path, { :class=>"navbar-brand" } %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'About', page_about_path %></li>
            <li><%= link_to 'Contact', page_contact_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Goals', goal_index_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out"></span> Logout
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-user"></span>
                  Sign Up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in"></span> Login
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <!-- <div class="row">
        <div class="col-lg-9"> -->
          <%= bootstrap_flash %>
          <%= yield %>
        <!-- </div> -->

        <!-- <div class="col-lg-3"> -->
          <!-- <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div> -->  <!--/.well -->
        <!-- </div> -->   <!--/span-->
      <!-- </div> -->     <!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>